n

diff --git a/src/MacVim/mvim b/src/MacVim/mvim
--- a/src/MacVim/mvim
+++ b/src/MacVim/mvim
@@ -12,23 +12,23 @@
 
 # Find Vim executable
 if [ -L "$0" ]; then
-    # readlink -f
-    curdir=`pwd -P`
-    self_path=$0
-    cd "`dirname $self_path`"
-    while [ -L "$self_path" ]; do
-        self_path=`readlink $self_path`
-        cd "`dirname $self_path`"
-        self_path=`basename $self_path`
-    done
-    binary="`pwd -P`/build/Release/MacVim.app/Contents/MacOS/Vim"
-    cd "$curdir"
+	# readlink -f
+	curdir=`pwd -P`
+	self_path=$0
+	cd "`dirname $self_path`"
+	while [ -L "$self_path" ]; do
+		self_path=`readlink $self_path`
+		cd "`dirname $self_path`"
+		self_path=`basename $self_path`
+	done
+	binary="`pwd -P`/../MacOS/Vim"
+	cd "$curdir"
 else
-    binary="`dirname "$0"`/../MacOS/Vim"
+	binary="`dirname "$0"`/../MacOS/Vim"
 fi
 if ! [ -x "$binary" ]; then
-    echo "Sorry, cannot find Vim executable."
-    exit 1
+	echo "Sorry, cannot find Vim executable."
+	exit 1
 fi
 
 # Next, peek at the name used to invoke this script, and set options
@@ -43,7 +43,7 @@ case "$name" in m*|g*|rm*|rg*) gui=true ;; esac
 
 # Logged in over SSH? No gui.
 if [ -n "${SSH_CONNECTION}" ]; then
-    gui=
+	gui=
 fi
 
 # Restricted mode
@@ -51,15 +51,15 @@ case "$name" in r*) opts="$opts -Z";; esac
 
 # vimdiff, view, and ex mode
 case "$name" in
-    *vimdiff)
-        opts="$opts -dO"
-        ;;
-    *view)
-        opts="$opts -R"
-        ;;
-    *ex)
-        opts="$opts -e"
-        ;;
+	*vimdiff)
+		opts="$opts -dO"
+		;;
+	*view)
+		opts="$opts -R"
+		;;
+	*ex)
+		opts="$opts -e"
+		;;
 esac
 
 # Last step:  fire up vim.
@@ -67,11 +67,11 @@ esac
 # not; we work around this when this script is invoked as "gvim" or "rgview"
 # etc., but not when it is invoked as "vim -g".
 if [ "$gui" ]; then
-    # Note: this isn't perfect, because any error output goes to the
-    # terminal instead of the console log.
-    # But if you use open instead, you will need to fully qualify the
-    # path names for any filenames you specify, which is hard.
-    exec "$binary" -g $opts ${1:+"$@"}
+	# Note: this isn't perfect, because any error output goes to the
+	# terminal instead of the console log.
+	# But if you use open instead, you will need to fully qualify the
+	# path names for any filenames you specify, which is hard.
+	exec "$binary" -g $opts ${1:+"$@"}
 else
-    exec "$binary" $opts ${1:+"$@"}
+	exec "$binary" $opts ${1:+"$@"}
 fi
